version: '3.7'

services:

  # Nginx for static file serving
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx  # The Dockerfile for Nginx
    container_name: nginx-server
    ports:
      - "80:80"  # Expose Nginx on port 80
    volumes:
      - ./nginx/static:/usr/share/nginx/html  # Bind static files to Nginx container
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Use the custom Nginx config
    networks:
      - analytics-net

  # Scala Backend (Akka HTTP)
  scala-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile  # Make sure this points to the Dockerfile for the Scala app
    container_name: scala-backend
    ports:
      - "8080:8080"  # Expose the Scala backend on port 8080
    networks:
      - analytics-net
  # api:
  #   image: api-image:latest
  #   container_name: api-server
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - kafka
  #     - redis
  #     - cassandra
  #   networks:
  #     - analytics-net

  # kafka:
  #   image: apache/kafka:latest
  #   container_name: kafka
  #   ports:
  #     - "9093:9093"
  #   environment:
  #     KAFKA_ADVERTISED_LISTENER: INSIDE:9093
  #     KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
  #     KAFKA_LISTENER_PORT: 9093
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #   depends_on:
  #     - zookeeper
  #   networks:
  #     - analytics-net

  # zookeeper:
  #   image: zookeeper:3.9.3
  #   container_name: zookeeper
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #   networks:
  #     - analytics-net

  # cassandra:
  #   image: cassandra:latest
  #   container_name: cassandra
  #   ports:
  #     - "9042:9042"
  #   networks:
  #     - analytics-net

  # redis:
  #   image: redis:latest
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - analytics-net

  # processing-service:
  #   image: processing-service:latest
  #   container_name: processing-service
  #   depends_on:
  #     - kafka
  #     - cassandra
  #     - redis
  #   networks:
  #     - analytics-net

networks:
  analytics-net:
    driver: bridge
