name: Test with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    services:
        docker:
          image: docker:19.03.12
          options: --privileged
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      # Set up Docker and Docker Compose
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build and test with Docker Compose
      run: |
        cd ./Excercise/Day04/
        docker-compose up redis nginx kafka cassandra scala-backend processing-backend scala-backend2 test --abort-on-container-exit --exit-code-from test
        docker-compose down